### ISSUE TITLE
Navbar Improvements

### ISSUE THREAD

**Issue by nickryall** [tofful/NavBar-ReactJS-demo#1]
This is looking great. Here is a couple of quick improvements that could be made:

1. Close the drop-down menu when the user clicks outside. i.e. On the document body.
2. Enable expand/collapse on the mobile version of the drop-down.
3. On the top item of the drop-down menu, change the color of the arrow to the active color (gray) on rollover.

**Comment by tofful** [comment]
- Issue #1 and #3 are solved and merged.
- Could you expand your explanation for issue #2? as I can see drop-down is working on mobile.

**Comment by nickryall** [comment]
For #2, I thought I was originally seeing the menu always open on mobile but it's working for me now.  Great work!
